pretrained_model_name_or_path = "runwayml/stable-diffusion-v1-5"
output_dir = "./ouput"
output_name = "ja_sd"
resolution = "192,192"
vae_batch_size = 32
cache_latents = false
save_precision = "fp16"
save_every_n_epochs = 8
xformers = true
max_train_epochs = 512
max_data_loader_n_workers = 4
persistent_data_loader_workers = true
seed = 42
gradient_checkpointing = false # true
mixed_precision = "fp16"
sample_every_n_epochs = 8
sample_prompts = "./configs/prompts_ja_sd.txt"
sample_sampler = "k_euler_a"
save_model_as = "safetensors"
optimizer_type = "adamw8bit"
learning_rate = 5e-4 # 1e-3
train_unet_only = true
network_module = "networks.lora"
network_dim = 64
network_args = [ "conv_dim=64" ] # , "rank_dropout=0.25" ]
noise_offset = 0.1
